In [112]:
%matplotlib notebook

import numpy
import pandas
import scipy

import matplotlib.pyplot as pyplot
import seaborn as sns
sns.set(color_codes=True)

from JZ:

Also - I have a question for you: I'm trying to assign Reviewers to letters of intent.  I figure you can help me, haha. :)

I have 151 LOIs in total, and would like each to be reviewed by 3 Reviewers out of a list of 22 (do I need 23?).  The max number of LOIs that I want each Reviewer to have is 20.

Say the Reviewers are A-V, and LOIs are #1-151. What are the combinations of Reviewers for each LOI?  Do you know how to figure this out?

I think this article might be relevant? https://stackoverflow.com/questions/48721368/combinations-with-max-repetitions-per-element

And I might not have explained it properly earlier:
We ran a grant competition with that had a Letter of Intent stage.  I need to assign 3 Reviewers to evaluate each LOI.  We got 151 LOIs in total. We have 22 Reviewers and I want them to review max 20 LOIs each.

So it's like selecting 3 items out of 22 items (order is not important), but each item can only appear 20 times max.

I want the combinations of Reviewers. :p  (I think I might need 23 Reviewers also).

In [93]:
N_loi = 151
N_reviewers = 22
N_reviewers_per_loi = 3

In [170]:
output_file_template = "assigned_reviewers_to_LOI_r{}x{}.txt"

In [100]:
reviewers = [chr(65+i) for i in range(N_reviewers)]
print(len(reviewers))
print(reviewers)

22
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V']


In [94]:
reviewer_list = []
while len(reviewer_list) < N_loi*N_reviewers_per_loi:
    reviewer_list.extend(reviewers)
print(len(reviewer_list))
reviewer_list = reviewer_list[:N_loi*N_reviewers_per_loi]
print(reviewer_list)

462
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'A', 

In [95]:
loi_list = []
for i in range(N_reviewers_per_loi):
    t = list(range(N_loi))
    numpy.random.shuffle(t)
    print(t[:10])
    loi_list.extend(t)
print(len(loi_list))

[76, 98, 82, 95, 25, 16, 75, 78, 104, 13]
[4, 6, 90, 48, 69, 119, 143, 71, 31, 52]
[97, 65, 89, 0, 3, 142, 88, 150, 52, 16]
453


In [96]:
df = pandas.DataFrame({"loi_ID":loi_list, "reviewer_ID":reviewer_list})
print(df.shape)
display(df.head())

(453, 2)


loi_ID reviewer_ID
0      76           A
1      98           B
2      82           C
3      95           D
4      25           E

In [97]:
# sanity check - does each LOI have 3 reviewers:
df.groupby("loi_ID").count().reviewer_ID.unique()

array([3])

In [98]:
check_loi_reviewer_groups_dict = {}

for i in range(N_loi):
    t = df.loc[df.loi_ID == i, "reviewer_ID"].to_list()
    t.sort()
    
    t_repr = t.__repr__()
    if t_repr in check_loi_reviewer_groups_dict:
        check_loi_reviewer_groups_dict[t_repr].append(i)
        print(i, t_repr, check_loi_reviewer_groups_dict[t_repr])
    else:
        check_loi_reviewer_groups_dict[t_repr] = [i]

40 ['B', 'H', 'T'] [28, 40]
131 ['H', 'N', 'P'] [18, 131]


In [99]:
df.groupby("reviewer_ID").count()

loi_ID
reviewer_ID        
A                21
B                21
C                21
D                21
E                21
F                21
G                21
H                21
I                21
J                21
K                21
L                21
M                21
N                20
O                20
P                20
Q                20
R                20
S                20
T                20
U                20
V                20

In [169]:
u = list()
for cur_loi_ID, vals in df.sort_values("loi_ID").groupby("loi_ID"):
    t = vals.reviewer_ID.to_list()
    t.sort()
#     print(cur_loi_ID, t)
    u.append(t)

assigned_df = pandas.DataFrame({"reviewer1":[x[0] for x in u]}, index=range(N_loi))
assigned_df.index.name = "loi_ID"
assigned_df["reviewer2"] = [x[1] for x in u]
assigned_df["reviewer3"] = [x[2] for x in u]
print(assigned_df.shape)
display(assigned_df.head())

(151, 3)


reviewer1 reviewer2 reviewer3
loi_ID                              
0              H         I         T
1              F         L         S
2              C         I         P
3              N         U         U
4              E         J         T

In [172]:
output_file = output_file_template.format(assigned_df.shape[0], assigned_df.shape[1])
print(output_file)
assigned_df.to_csv(output_file, sep="\t")

assigned_reviewers_to_LOI_r151x3.txt


In [154]:
######################################
##### switchng to combinatorics method
######################################
N_reviewer_combinations = scipy.special.comb(N_reviewers, 3, exact=True)
limit = 21

reviewer_combinations = numpy.zeros((N_reviewer_combinations, 4), dtype=int)
print(reviewer_combinations.shape)
# reviewer_combinations[:] = numpy.nan

used_reviewers = numpy.zeros(N_reviewers)

index = 0
for i in range(N_reviewers):
    for j in range(i+1, N_reviewers):
        for k in range(j+1, N_reviewers):
            reviewer_combinations[index, :3] = [i, j, k]
            
            if (used_reviewers[i] < limit) and (used_reviewers[j] < limit) and used_reviewers[k] < limit:
                reviewer_combinations[index, 3] = 1
                used_reviewers[[i,j,k]] = used_reviewers[[i,j,k]] + 1
            
            index = index + 1

print(used_reviewers)
print(len(reviewer_combinations))
print(reviewer_combinations[:10])

(1540, 4)
[21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21.
 19. 18. 14. 12.]
1540
[[ 0  1  2  1]
 [ 0  1  3  1]
 [ 0  1  4  1]
 [ 0  1  5  1]
 [ 0  1  6  1]
 [ 0  1  7  1]
 [ 0  1  8  1]
 [ 0  1  9  1]
 [ 0  1 10  1]
 [ 0  1 11  1]]


In [163]:
# p0 = reviewer_combinations[:, 0] == 0
# p1 = reviewer_combinations[:, 1] == 1
# p2 = reviewer_combinations[:, 2] == 2
# reviewer_combinations[p0 & p1 & p2, 3] = 0
reviewer_combinations[-5, 3] = 1
print(reviewer_combinations[-5,:])

p0 = reviewer_combinations[:, 3] == 1
print(sum(p0))

[17 20 21  1]
148


In [121]:
#######################
# attempt w/ sorting combinations
#######################
reviewer_comb_choices = list(range(N_reviewer_combinations))
numpy.random.shuffle(reviewer_comb_choices)
print(reviewer_comb_choices[:10])

[1376, 127, 207, 629, 1207, 34, 451, 710, 841, 788]


In [125]:
for i in range(N_loi):
    cur_comb_choice = reviewer_comb_choices[i]
    reviewer_combinations[cur_comb_choice,3] = 1
print(reviewer_combinations[reviewer_combinations[:,3] == 1])

[[ 0  1  9  1]
 [ 0  1 14  1]
 [ 0  2 17  1]
 [ 0  3 16  1]
 [ 0  5  6  1]
 [ 0  5 21  1]
 [ 0  6  8  1]
 [ 0  6 19  1]
 [ 0  7 19  1]
 [ 0  8 17  1]
 [ 0  9 18  1]
 [ 0  9 21  1]
 [ 0 10 17  1]
 [ 0 11 13  1]
 [ 0 11 20  1]
 [ 0 14 18  1]
 [ 0 15 17  1]
 [ 0 16 17  1]
 [ 0 16 19  1]
 [ 0 19 20  1]
 [ 0 20 21  1]
 [ 1  2  7  1]
 [ 1  2 17  1]
 [ 1  4  6  1]
 [ 1  4  7  1]
 [ 1  6 10  1]
 [ 1  7 16  1]
 [ 1  8 13  1]
 [ 1 11 14  1]
 [ 1 11 15  1]
 [ 1 14 15  1]
 [ 1 16 19  1]
 [ 1 17 18  1]
 [ 1 18 19  1]
 [ 2  3  8  1]
 [ 2  3 12  1]
 [ 2  3 13  1]
 [ 2  3 16  1]
 [ 2  4  8  1]
 [ 2  4 13  1]
 [ 2  4 17  1]
 [ 2  5 20  1]
 [ 2  6  7  1]
 [ 2  6 10  1]
 [ 2  6 19  1]
 [ 2  7  9  1]
 [ 2  7 14  1]
 [ 2  9 12  1]
 [ 2  9 19  1]
 [ 2 10 12  1]
 [ 2 10 21  1]
 [ 2 11 14  1]
 [ 2 13 17  1]
 [ 2 13 19  1]
 [ 2 15 18  1]
 [ 2 16 21  1]
 [ 3  6 12  1]
 [ 3  6 13  1]
 [ 3  7 18  1]
 [ 3  8 10  1]
 [ 3 11 14  1]
 [ 3 11 19  1]
 [ 3 12 21  1]
 [ 3 14 17  1]
 [ 3 15 16  1]
 [ 3 16 18  1]
 [ 3 18 21

In [129]:
p1 = reviewer_combinations[:,0] == 0
p2 = reviewer_combinations[:,1] == 0
p3 = reviewer_combinations[:,2] == 0

print(sum(p1), sum(p2), sum(p3))
print(sum(p0 & (p1 | p2 | p3)))

for i in range(N_reviewers):
    p1 = reviewer_combinations[:,0] == i
    p2 = reviewer_combinations[:,1] == i
    p3 = reviewer_combinations[:,2] == i
    
    p_loc = p1 | p2 | p3
    
    print(sum(p1), sum(p2), sum(p3), sum(p_loc), sum(p0 & p_loc))

151
210 0 0
21
210 0 0 210 21
190 20 0 210 15
171 38 1 210 25
153 54 3 210 16
136 68 6 210 18
120 80 10 210 11
105 90 15 210 25
91 98 21 210 27
78 104 28 210 17
66 108 36 210 23
55 110 45 210 19
45 110 55 210 23
36 108 66 210 17
28 104 78 210 24
21 98 91 210 19
15 90 105 210 17
10 80 120 210 28
6 68 136 210 23
3 54 153 210 22
1 38 171 210 26
0 20 190 210 18
0 0 210 210 19
